// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_027ddebb() {
    type $$ComponentProps = {a: any, class?: any};
    type $$Events = {};

    let { a, class: className = $bindable() }: $$ComponentProps = $props();
    ;(async () => {
        // template type-check body (incremental)
    });
    void className;
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: __svn_$$bindings('class'), exports: undefined as any as ({}) };
}
$$render_027ddebb;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_027ddebb>>['props'],
    Awaited<ReturnType<typeof $$render_027ddebb>>['exports'],
    Awaited<ReturnType<typeof $$render_027ddebb>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

