// === input.svelte ===
// generated by svelte-check-native; do not edit
declare const a: { [key: string]: any } & ((...args: any[]) => any);
namespace A {
    export type Abc = typeof a
}
interface Abc {
    foo: A.Abc
}
async function $$render_384d5614() {
    type $$Events = {};

const a = 1;

             
                              
 

               
              
 

let {}: Abc = $props();
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: undefined as any as (Abc), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: __svn_$$bindings(), exports: undefined as any as ({}) };
}
$$render_384d5614;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_384d5614>>['props'],
    Awaited<ReturnType<typeof $$render_384d5614>>['exports'],
    Awaited<ReturnType<typeof $$render_384d5614>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

