// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_491a605d<A>() {

                       

           let a!: A;
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:options", {
            "accessors": true,
        });
        }
    });
    void a;
    return { props: undefined as any as ({ a: A; }), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({ a: A; }) };
}
$$render_491a605d;
declare class __svn_Render_491a605d<A> {
    props(): Awaited<ReturnType<typeof $$render_491a605d<A>>>['props'];
    events(): Awaited<ReturnType<typeof $$render_491a605d<A>>>['events'];
    slots(): Awaited<ReturnType<typeof $$render_491a605d<A>>>['slots'];
    bindings(): Awaited<ReturnType<typeof $$render_491a605d<A>>>['bindings'];
    exports(): Awaited<ReturnType<typeof $$render_491a605d<A>>>['exports'];
}
interface $$IsomorphicComponent {
    new <A>(options: import('svelte').ComponentConstructorOptions<ReturnType<__svn_Render_491a605d<A>['props']>>): import('svelte').SvelteComponent<ReturnType<__svn_Render_491a605d<A>['props']>, ReturnType<__svn_Render_491a605d<A>['events']>, ReturnType<__svn_Render_491a605d<A>['slots']>> & { $$bindings?: ReturnType<__svn_Render_491a605d<A>['bindings']> } & ReturnType<__svn_Render_491a605d<A>['exports']>;
    <A>(internal: unknown, props: ReturnType<__svn_Render_491a605d<A>['props']>): ReturnType<__svn_Render_491a605d<A>['exports']> & { $set?: any; $on?: any };
    z_$$bindings?: ReturnType<__svn_Render_491a605d<any>['bindings']>;
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default<A> = InstanceType<typeof __svn_component_default<A>>;
export default __svn_component_default;

